<a href="https://www.kaggle.com/code/peteradelgado/drug-classification-code?scriptVersionId=134663690" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
#Basic Reading
import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold,train_test_split,cross_val_score,RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

In [2]:
#This imports the excel file to python
data = pd.read_csv('/kaggle/input/drug-classification/drug200.csv')

In [3]:
#This reads the excel file and provides the first 5 rows
data.head(10)

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY
5   22   F  NORMAL        HIGH    8.607  drugX
6   49   F  NORMAL        HIGH   16.275  DrugY
7   41   M     LOW        HIGH   11.037  drugC
8   60   M  NORMAL        HIGH   15.171  DrugY
9   43   M     LOW      NORMAL   19.368  DrugY

In [4]:
#This would convert the categorical data into numerical values
for col in data:
    data[col]=data[col].astype('category').cat.codes

#data['Sex'].replace(['F','M'],['0','1'],regex = True)
#data['BP'].replace(['LOW','NORMAL','HIGH'],['0','1','2'], regex = True)
#data['Cholesterol'].replace(['NORMAL','HIGH'],['0','1'], regex = True)
#data['Drug'].replace(['drugA','drugB','drugC','drugX','DrugY'],['0','1','2','3','4'], regex = True)

In [5]:
#This reads the altered excel file and provides the first 5 rows.
data.head()

   Age  Sex  BP  Cholesterol  Na_to_K  Drug
0    8    0   0            0      167     0
1   30    1   1            0       89     3
2   30    1   1            0       43     3
3   12    0   2            0       10     4
4   44    0   1            0      133     0

In [6]:
drug = data['Drug']
data = data.drop('Drug', axis = 1)

In [7]:
xtrain,xtest,ytrain,ytest=train_test_split(data,drug,test_size=0.25,stratify=drug)

In [8]:
xtrain.shape,ytrain.shape,xtest.shape,ytest.shape

((150, 5), (150,), (50, 5), (50,))

In [9]:
cv=StratifiedKFold(n_splits=10)
clf=RandomForestClassifier(class_weight='balanced')
result=cross_val_score(clf,xtrain,ytrain,cv=cv,verbose=1,n_jobs=-1).mean()
result

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:    2.9s finished

0.9933333333333334